### ISSUE TITLE
Inputs not parsed properly.

### ISSUE THREAD

**Issue by FireBrandMint** [Carbone13/godot-rollback-cs#2]
The input dictionary can't access entries by index for some reason.

(forget all that's below this line, my fix worked but it stopped working for no reason, i have no idea how)

For some reason godot dictionaries in c# doesn't actually registers your entry just by calling 'dictionary[entry] = value', it only registers if you call 'dictionary.Add(entry, value)', and because the input parsing in 'ReceiveInputTick' uses the faulty method, you can't get inputs by entry, leading to very nonsensical bugs.

Very simple fix: change line 939 of the SyncManager from "allRemoteInput[int.Parse(entry.Key)] = entry.Value;" to "allRemoteInput.Add(int.Parse(entry.Key),entry.Value);"

EDIT: strange, this fix doesn't work all the time, what the hell? It stopped working!

**Comment by lmichaudel** [comment]
Thanks for pointing this out. I also discovered that the GD.Hash(dictionary) was not the same as dictionary.hash(), therefore the way I compared the dictionary was wrong

**Comment by lmichaudel** [comment]
More investigation is needed, I think some bugs remains
Once I implement a cleaner way to serialize, send & parse inputs, bugs may vanish

**Comment by FireBrandMint** [comment]
> More investigation is needed, I think some bugs remains
> Once I implement a cleaner way to serialize, send & parse inputs, bugs may vanish

Hey, i made a class for this, if you are unable to solve this problem with the godot dictionary.

```
using Godot;
using System;
using System.Text;
using System.Collections.Generic;

public class InputsDict
{
    public Dictionary<int, string> inpDict = new Dictionary<int, string>();

    public string this[int key]
    {
        get=>inpDict[key.GetHashCode()];
        set=>inpDict.Add(key, value);
    }

    public bool ContainsKey (int key) => inpDict.ContainsKey(key);

    public Dictionary<int, string> GetRootDictionary () => inpDict;

    public byte[] Serialize ()
    {
        var bytes = new List<byte>();

        bytes.AddRange(BitConverter.GetBytes((Int32) inpDict.Count));

        foreach (var entry in inpDict)
        {
            bytes.AddRange(BitConverter.GetBytes((Int32) entry.Key));
            byte[] strEncoded = Encoding.ASCII.GetBytes(entry.Value);
            bytes.AddRange(BitConverter.GetBytes((Int32) strEncoded.Length));
            bytes.AddRange(strEncoded);
        }
        return bytes.ToArray();
    }

    public static InputsDict Deserialize (byte[] data)
    {
        var toReturn = new InputsDict();
        int CurrByte = 0;
        
        int elementAmount = BitConverter.ToInt32(data, CurrByte);
        CurrByte+=4;

        for (int i = 0; i<elementAmount; ++i)
        {
            int key = BitConverter.ToInt32(data, CurrByte);
            CurrByte+=4;

            int valueLenght = BitConverter.ToInt32(data, CurrByte);
            CurrByte+=4;

            string value = Encoding.ASCII.GetString(data, CurrByte, valueLenght);
            CurrByte+= valueLenght;

            toReturn[key] = value;
        }

        return toReturn;
    }
}
```

**Comment by lmichaudel** [comment]
Nice, last commit implement this, I created 2 additional class to prepare for the migration. I'm going on vacation tomorrow for one week so I will not be able to work on it soon. Feel free to do so, I'll accept PR

**Comment by FireBrandMint** [comment]
Have a good vacation then, maybe i will get around installing github on vscode to try.

EDIT: i did it, but oh god it was hard.

**Comment by FireBrandMint** [comment]
This issue will be fixed with my pull request, if anyone else is reading this just download my fork of this repo because the problem is already solved there.

**Comment by lmichaudel** [comment]
Should be pushed to the master branch around Monday 👍
