### ISSUE TITLE
Float might cause desync over time.

### ISSUE THREAD

**Issue by FireBrandMint** [Carbone13/godot-rollback-cs#5]
Floating points are very infamous for not being calculated properly and causing a lot of issues, including the possibility that they give different results on different machines.

The "solutions" i know (honestly they are pretty risky, there might be something else that's better):

- Correct floats with some calculation related to scale. (might not solve the issue tbh, for example: the difference between the resulting move_and_collide or just changing the position could theoretically be more than the scale, causing a bigger desync than if it didn't have this calculation)

- Make the server send the entire world state every X seconds and resimulate. (might be too much for UDP, and it might take a lot of work, but it's the safer option. If you try this let me know how i can help you, i'm very bad at this stuff but i can try)

**Comment by lmichaudel** [comment]
Hey there, I suggest reading my last comment on your PR, it explains the situation well.
Also I'm working on a 100% deterministic physics. It still need more functionalities but once coupled with this repo, it could give good result.
About the second solution it can be something to implement, I mean if people don't want it they may just turn it off. The good point is that such logic is already implemented at the end of the sync manager, it's only comparing state and crying if they don't match and the send logic is not abstracted to the Network Adaptor, but that's not a big amount of work tbh 🙂

**Comment by guliver-jham** [comment]
Okay, now i read it.

**Comment by FireBrandMint** [comment]
Oh that's right, now i'm reading it, you're talking about RemotEstateMismatch, thank you for you patience,

**Comment by lmichaudel** [comment]
Yes exactly, now the logic need to be determined, if we discover a mismatch we need a strong logic to determine which one is right

**Comment by lmichaudel** [comment]
Yes but as this is 100% p2p their is no clear server, but well most of the game will implement a "group/game master" guy, so it should not be a problem 🙂

**Comment by lmichaudel** [comment]
As long as everyone end up in the same state, that's all we want 😅

**Comment by guliver-jham** [comment]
Yeah, that sounds very good,

**Comment by guliver-jham** [comment]
Just leaving this here, there's a problem with sending the world state: if the player changed input and the server sends them the state before the input gets rolled back, that could cause a desync.
